In [1]:
import numpy as np
import pandas as pd

In [3]:
#Q1 : WAP to take 10 inputs from the user as comma separated and stored into a 5*2 matrix

ip = input("Enter Number with ',' separated : ")
ip = np.array(ip.split(','))
ip.reshape(5,2)
print(ip)


['1' '2' '3' '4' '5' '6' '7' '8' '9' '0']


In [15]:
#Q2 : WAP to create a 4*5 matrix and reverse the elements of 3rd row only.

arr = np.array(np.random.randint(0,10,(4,5)))
print(arr)
print("After reversing elements of 3rd row :")
arr[2,:] = arr[2,::-1]
print(arr)

[[3 5 9 0 5]
 [0 4 1 4 8]
 [5 5 6 9 5]
 [0 0 5 0 7]]
After reversing elements of 3rd row :
[[3 5 9 0 5]
 [0 4 1 4 8]
 [5 9 6 5 5]
 [0 0 5 0 7]]


In [17]:
#Q3 : WAP to create a 4*5 matrix and reverse the elements of 2rd column only

arr = np.array(np.random.randint(0,10,(4,5)))
print(arr)
print("After reversing elements of 2nd column :")
arr[:,1] = arr[::-1,1]
print(arr)

[[8 4 5 3 7]
 [1 9 6 8 2]
 [8 6 5 6 2]
 [9 9 2 3 4]]
After reversing elements of 2nd column :
[[8 9 5 3 7]
 [1 6 6 8 2]
 [8 9 5 6 2]
 [9 4 2 3 4]]


In [52]:
#Q4 : Write a NumPy program to test whether each element of a 1-D array is also present in a second array

arr1 = np.array(np.random.randint(1,7,10))
arr2 = np.array(np.random.randint(5,8,(3,3)))
print(arr1)
print(arr2)
np.isin(arr1,arr2)

[3 1 3 3 3 5 3 1 6 3]
[[5 6 6]
 [5 7 6]
 [6 6 6]]


array([False, False, False, False, False,  True, False, False,  True,
       False])

In [19]:
#Q5 : Write a NumPy program to find common values between two arrays

arr1 = np.array([1,5,2,3,6,4])
arr2 = np.array([10,5,3,2,7,6,9,1,4])
print(np.intersect1d(arr1,arr2))

[1 2 3 4 5 6]


In [68]:
#Q6 : Take two 1-D array and make a new 1D array where all elements are greater than 5.

arr1 = np.array(np.random.randint(1,7,10))
arr2 = np.array(np.random.randint(2,8,10))
print(arr1)
print(arr2)
newArr = np.concatenate([arr1,arr2])
newArr= newArr[newArr>5]
print(newArr)


[4 4 4 2 4 4 5 2 5 3]
[7 5 7 5 2 3 6 3 5 4]
[7 7 6]


In [44]:
#Q7 : You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

ip = input("Enter numbers with ',' separated : ")
ip = np.array(ip.split(','))
ip[:] = ip[::-1]
ip = ip.astype('float64')
print(ip)

[-10.  -8.   4.   3.   2.   1.]


In [49]:
#Q8 

nmp = input("NMP :").split()
n = int(nmp[0])
m = int(nmp[1])
p = int(nmp[2])
ans = []
for i in range(n):
    temp = []
    temp.append(input().split())
    ans.append(temp)
for i in range(m):
    temp = []
    temp.append(input().split())
    ans.append(temp)

ans = np.array(ans)
ans = ans.astype('int')
print(ans)

[[[1 2]]

 [[1 2]]

 [[1 2]]

 [[1 2]]

 [[3 4]]

 [[3 4]]

 [[3 4]]]
